---
apiVersion: v1
kind: Namespace
metadata:
  name: customer1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: customer1
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: front-end
          image: gardnera/canarytester:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: DT_CUSTOM_PROP
              value: "Version=v1"

---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: customer1
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: customer1-ingress
  namespace: customer1
spec:
  rules:
  - host: customer1.INGRESS-PLACEHOLDER
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          serviceName: web
          servicePort: 80
