---
apiVersion: v1
kind: Namespace
metadata:
  name: customer3

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: customer3
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: front-end
          image: gardnera/canarytester:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: customer3
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: customer3-ingress
  namespace: customer3
spec:
  rules:
  - host: customer3.INGRESS-PLACEHOLDER
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          serviceName: web
          servicePort: 80